# Generated by Django 5.0.7 on 2024-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
